# Generated by Django 5.2.12 on 2026-03-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("logo", models.ImageField(upload_to="companies/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
