# Generated by Django 5.2.12 on 2026-03-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hero_carousel/"
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=200)),
                ("subtext", models.CharField(blank=True, max_length=300)),
                ("cta_text", models.CharField(blank=True, max_length=50)),
                ("cta_link", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
