# Generated by Django 4.2.15 on 2026-04-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero_carousel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carouselslide",
            name="image",
        ),
        migrations.AddField(
            model_name="carouselslide",
            name="image_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
