# Generated by Django 4.2.15 on 2026-04-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sanitary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanitaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("image_key", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="sanitaryproduct",
            name="image",
        ),
        migrations.AddField(
            model_name="sanitaryproduct",
            name="image_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name="sanitaryproduct",
            name="category",
        ),
        migrations.AddField(
            model_name="sanitaryproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="sanitary.sanitarycategory",
            ),
        ),
    ]
