# Generated by Django 4.2.15 on 2026-04-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_created_at"),
        ("sanitary", "0002_sanitarycategory_remove_sanitaryproduct_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanitaryproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sanitary_products",
                to="products.category",
            ),
        ),
        migrations.DeleteModel(
            name="SanitaryCategory",
        ),
    ]
